### ISSUE TITLE
i have created a startup script

### ISSUE THREAD

**Issue by GrumpyOet** [iiegor/slither#16]
**Start.sh in the slither folder look like this:**

```
#!/bin/sh

sudo bash Desktop/slither/script/Slither
```

and 

**Slither executable file in the script folder look like this**

```
#!/bin/sh

	cd "$( dirname "$0" )"
		cd ..

		./script/run
```

if have send the files to your mail

watch it in github [click here](https://github.com/GrumpyOet/slither)

(i have forked your repository)

**Comment by iiegor** [comment]
@GrumpyOet there is already an startup script at ``script`` folder. Also you can execute the server running ``npm start``, why another script?

**Comment by GrumpyOet** [comment]
But if you do script/run with port 443 you will get a error (its need to load with root)

**Comment by GrumpyOet** [comment]
And with this script you only click on start.sh and its start
