### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ElMay0r** [iiegor/slither#17]
[Server][ERROR] Unhandled message s -  null
Snake going to 250
[Server][ERROR] Unhandled message s -  null
[Server][ERROR] Unhandled message s -  null

**Comment by morenja** [comment]
Me too have that problem, and you can't move?

**Comment by thereis** [comment]
The problem is not solved, it will be solved after some updates...

**Comment by iiegor** [comment]
@thereis that's, closing this.
