### ISSUE TITLE
Error !!!

### ISSUE THREAD

**Issue by Roken120** [iiegor/slither#19]
[Application][INFO] Starting the server in dev at port 888...
[Server][INFO] Listening on port 888
[Server][DEBUG] A new snake called  was connected!
[Server][ERROR] Unhandled message û -  null
[Server][ERROR] Unhandled message T -  null
[Server][ERROR] Unhandled message g -  null
[Server][ERROR] Unhandled message � -  null
[Server][ERROR] Unhandled message | -  null
[Server][ERROR] Unhandled message U -  null
[Server][ERROR] Unhandled message X -  null
[Server][ERROR] Unhandled message V -  null
[Server][ERROR] Unhandled message X -  null
[Server][ERROR] Unhandled message _ -  null
[Server][ERROR] Unhandled message b -  null
[Server][ERROR] Unhandled message a -  null
[Server][ERROR] Unhandled message ` -  null
[Server][ERROR] Unhandled message c -  null
[Server][ERROR] Unhandled message j -  null
[Server][ERROR] Unhandled message n -  null
[Server][ERROR] Unhandled message j -  null
[Server][ERROR] Unhandled message i -  null
[Server][ERROR] Unhandled message d -  null
[Server][ERROR] Unhandled message a -  null
[Server][ERROR] Unhandled message j -  null
[Server][ERROR] Unhandled message o -  null
On connect by Plither help me please

**Comment by thereis** [comment]
This feature is not working, come back later for the new updates.
