### ISSUE TITLE
Increase vector Snake direction code

### ISSUE THREAD

**Issue by GrumpyOet** [iiegor/slither#20]
var incX = ((float)Math.Cos((Math.PI / 180) * this.Snake.CurrentAngle));
var incY = ((float)Math.Sin((Math.PI / 180) * this.Snake.CurrentAngle));

That for calculate the good increase vector for snake direction
(You need to convert you angle to radian like this)

From nightwolf93

**Comment by nightwolf93** [comment]
Mention me next time ;)

**Comment by GrumpyOet** [comment]
Sorry i forgot it

**Comment by nightwolf93** [comment]
Thank

**Comment by iiegor** [comment]
@GrumpyOet @nightwolf93 thanks, implemented.
