### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by sonia123456** [iiegor/slither#23]
Which port runs the game?
I tried 443 but does not work

**Comment by RowanHarley** [comment]
Look at the sample wiki page in the issues. It shows you how to connect there

**Comment by sonia123456** [comment]
Sorry, but I did not understand.
I've been up the folder and copied the way i did " npm install" in "cmd " and then ran the script "run" but do not know which port is running the game

**Comment by RowanHarley** [comment]
it should be running on port 443

**Comment by sonia123456** [comment]
when I put this port , says that "Upgrade Required"

**Comment by Qasimmodo** [comment]
You dont direct connect to a site, its not a client, it's a game-server. use http://slitherplus.io/ if your a noob. You can put the IP in there. It's essentially the same as the JavaScript Console.

**Comment by sonia123456** [comment]
Yes I am Noob , I'm a girl, but then it is not possible to emulate server on the computer and play in browser

**Comment by thereis** [comment]
The current version isn't playable yet, so becareful. I recomend you to NOT waste your time with alpha releases...
