### ISSUE TITLE
Stop Using CoffeeScript

### ISSUE THREAD

**Issue by goryfigment** [iiegor/slither#25]
If you want a faster response time use regular javascript which includes the opportunity to optimize the code even more. Coffescript can only be as fast as javascript, but never faster. This is important to consider to reduce lag and latency. 

For more details visit this site, http://stackoverflow.com/questions/9047276/is-coffeescript-faster-than-javascript

**Comment by Qasimmodo** [comment]
I have to agree with OP.

**Comment by iiegor** [comment]
I would agree with you but the server is very simple so if we switch to javascript I think there aren't things you can really optimize.

Just to clarify, the only reason I'm using coffeescript is the syntax which is more fast to write and test things.

**Comment by goryfigment** [comment]
Ok if this is the actual slither.io game, I find myself lagging more often then not at the lowest detail. The servers are not to blame since I ping to them well and I have verizon fios. My computer is a gaming computer from Alienware and I promise I have the specs to play a 2d game. If I can play 3d games that need to render plenty more then this game with no lag then I should be able to play slither with any computer spec. I will close this since this is not an actual issue, but maybe refactoring of the code to reduce lag could be in your team's consideration.

**Comment by ItzLevvie** [comment]
For the best performance, you can use JS (with ES6) --> JXCore (since NodeJS can't use all of the cores, so here comes the beast) --> JS Compressor (I tried to obfuscate the JS, but did make the server a bit less responsive)

js2.coffee (Use this, if you're moving from CoffeeScript to JavaScript)
jscompress.com (Use this, if you want to make your JS a bit faster by compressing and minifying)

**Comment by iiegor** [comment]
I will take a look at JXCore and maybe when the development is more advanced I will do some benchmarks but at the moment there is practically nothing to optimize. Compressing the server source code doesn't makes any sense since it's running on the backend.
