### ISSUE TITLE
Can this run on it's own?

### ISSUE THREAD

**Issue by RowanHarley** [iiegor/slither#27]
I've downloaded this private server and been using it for a while but the snake doesnt seem to move very well. Is there another github repository I need to run this or what?

**Comment by Qasimmodo** [comment]
If you read..... you'd see "This is currentely an extremely active development, and you probably shouldn't use it unless you like broken software."

**Comment by RowanHarley** [comment]
Ok, thanks @Qasimmodo that explains all the bugs!
