### ISSUE TITLE
Help with console connection

### ISSUE THREAD

**Issue by RowanHarley** [iiegor/slither#29]
Just a quick question, what does sos = [{ ip: "localhost", po: 8080, ac: 34, ptm: 121 }] mean? I know the first 2 parts are up and port but what do the last 2 mean?

**Comment by iiegor** [comment]
I think that "ptm" is refered to the ``ping time``, the other one I don't know.

**Comment by Logan7432** [comment]
@iiegor Slither.io when i type that stuff in it wont connect to my server..
