### ISSUE TITLE
Address

### ISSUE THREAD

**Issue by awesome171203** [iiegor/slither#31]
The Sever Cannot find my IP so the server doesn't launch. Is there A Way to Type In A IP So It Doesn't Have To Do It For You?

**Comment by awesome171203** [comment]
Title Ment To Be Address

**Comment by iiegor** [comment]
It's strange, did you get some error message?

Anyway, at the moment the only way you can set the host is replacing [this line](https://github.com/iiegor/slither/blob/master/src/server.coffee#L35) for the following:
```coffeescript
@server = new ws.Server {@port, host: 'YOUR ADDRESS', path: '/slither'}, =>
```

**Comment by awesome171203** [comment]
![screenshot 2016-04-23 12 16 48](https://cloud.githubusercontent.com/assets/18631717/14762647/78343ff8-094d-11e6-9cc5-e82eea035f40.png)

This Was The Error Message And It's Still Happening. It Said Unknown Number

**Comment by awesome171203** [comment]
is there any way of fixing this!

**Comment by iiegor** [comment]
Why you are trying to listen to your private ip address? Just use 127.0.0.1.
