### ISSUE TITLE
Cannot connect

### ISSUE THREAD

**Issue by cmdpwnd** [iiegor/slither#32]
Ran:

npm install
npm start

Output:

[Application][DEBUG] You are running slither-server 0.0.9
[Application][INFO] Starting the server in dev at port 443...
[Server][INFO] Listening for connections

-------------------------------------------

https://127.0.0.1
or
127.0.0.1:443

Message:

Upgrade Required

**Comment by ItzLevvie** [comment]
Read https://github.com/iiegor/slither/issues/6#issuecomment-211077549
