### ISSUE TITLE
will yo

### ISSUE THREAD

**Issue by eralpcicekdagi** [iiegor/slither#34]
1- will you share web files
2- will you add chatbox
3- is it working but without really realesed version

**Comment by Qasimmodo** [comment]
You mean the client side of the project? That isn't ready yet, since they're focusing on the gameserver.

**Comment by Logan7432** [comment]
Yes, Please make a client side of the project! and also a chatbox!

**Comment by morenja** [comment]
First fix the server side then make client..

**Comment by iiegor** [comment]
@morenja and who said that won't be like you said?

**Comment by morenja** [comment]
When a new update comes out?
