### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by NoorAgario** [iiegor/slither#37]
using port 8080
Application][DEBUG] You are running slither-server 0.0.9
[Application][INFO] Starting the server in dev at port 8080...
[Server][INFO] Listening for connections

When trying to connect this happens
SCRIPT12017: WebSocket Error: SECURITY_ERR, Cross zone connection not allowed

Please tell me how to connect ,thanks

**Comment by iiegor** [comment]
See http://stackoverflow.com/questions/31541102/microsoft-edge-does-not-allow-localhost-loopback-for-websockets, it's not related with the server.
