### ISSUE TITLE
Skype

### ISSUE THREAD

**Issue by CineXMike** [iiegor/slither#38]
Please send me your Skype at mike@mikesantifort.nl

**Comment by CineXMike** [comment]
Is this posible please.

**Comment by iiegor** [comment]
@CineXMike Sorry, I don't use skype. If you have any question, send me an [email](dextrackmedia@gmail.com) or ask here.

**Comment by CineXMike** [comment]
Please send me an email then

**Comment by iiegor** [comment]
dextrackmedia@gmail.com
