### ISSUE TITLE
Snake wont move

### ISSUE THREAD

**Issue by helma27** [iiegor/slither#39]
I know some people already reported this, but in the latest release v0.0.10, it still gave me pose like this
![Image of Yaktocat](http://i.imgur.com/V2C8AoX.png)
This snake wont move no matter what, even i poke his eye...

And the console still give me this error...
![Image of Yaktocat](http://i.imgur.com/e8BXiKC.png)

EDIT:
I'm using Ubuntu 14 vps
and use `npm start` to start it

**Comment by thereis** [comment]
The source isn't finished... just download and try to code yourself and share the solution...

**Comment by iioel** [comment]
@helma27 Check #42

**Comment by helma27** [comment]
@iioel it working now!
Thanks bro :+1: 
@iiegor you must check his pull

**Comment by iiegor** [comment]
@helma27 closing this since the pull request was merged.

**Comment by helma27** [comment]
But i still cannot see the food

**Comment by iiegor** [comment]
@helma27 read https://github.com/iiegor/slither/issues/41#issuecomment-214782874
