### ISSUE TITLE
Snake moves quickly and there is no food 

### ISSUE THREAD

**Issue by linushg111** [iiegor/slither#41]
Ok i have a problem with this server when i join the server i am realllllly fat and i men relay fast and there is no food and i am not on the mini map.

**Comment by NoorAgario** [comment]
same , my snake move very fast and I cant eat food it just spawn and u cant rly do anything

**Comment by Pumpkin21** [comment]
Didn't you read the README people?!
"This is currently under extremely active development, and you probably shouldn't use it unless you like broken software.."

**Comment by RowanHarley** [comment]
This is because iiegor removed this to stop the lag from the snake. It will be re-implemented soon though I'd say

**Comment by linushg111** [comment]
ok soory hope you can fix it :-) do want to be angry

2016-04-26 12:39 GMT+02:00 Pumpkin21 <notifications@github.com>:
