### ISSUE TITLE
npm start fail

### ISSUE THREAD

**Issue by phoenixg** [iiegor/slither#47]
```
[phoenix@PhxMBP slither (master)]$ npm install

> utf-8-validate@1.2.1 install /Users/phoenix/mine/tmp/slither/slither/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node

> bufferutil@1.2.1 install /Users/phoenix/mine/tmp/slither/slither/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
object-keys@1.0.9 node_modules/object-keys

  1 module.exports = {
semver@5.1.0 node_modules/semver

coffee-script@1.10.0 node_modules/coffee-script

ws@0.8.1 node_modules/ws
├── options@0.0.6
├── ultron@1.0.2
├── utf-8-validate@1.2.1 (bindings@1.2.1, nan@2.3.0)
└── bufferutil@1.2.1 (bindings@1.2.1, nan@2.3.0)

chalk@1.1.3 node_modules/chalk
├── ansi-styles@2.2.1
├── supports-color@2.0.0
├── escape-string-regexp@1.0.5
  1 module.exports = {
├── strip-ansi@3.0.1 (ansi-regex@2.0.0)
└── has-ansi@2.0.0 (ansi-regex@2.0.0)
[phoenix@PhxMBP slither (master)]$ npm start

> slither-server@0.0.10 start /Users/phoenix/mine/tmp/slither/slither
> node ./bin/slither

[Application][DEBUG] You are running slither-server 0.0.10
[Application][INFO] Starting the server in dev at port 443...
[Server][ERROR] listen EACCES 0.0.0.0:443 -  { [Error: listen EACCES 0.0.0.0:443]
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 443 }
```

**Comment by Blakko** [comment]
Change the port in `config/default.js`.
You have no priviledges to use the 443 port

**Comment by SkorrloreGaming** [comment]
Make sure you have "npm install" executed in the root directory, also you must have that port forwarded. You can also change the port in config\default.js. I changed the line personally to "'port': 4413,".

**Comment by phoenixg** [comment]
It's started, how do I type URL to play? 
```
[phoenix@PhxMBP slither (master ✗)]$ npm start

> slither-server@0.0.10 start /Users/phoenix/mine/tmp/slither/slither
> node ./bin/slither

[Application][DEBUG] You are running slither-server 0.0.10
[Application][INFO] Starting the server in dev at port 4413...
[Server][INFO] Listening for connections
```

**Comment by SkorrloreGaming** [comment]
You need a mod on slither.io to allow you to connect to a private server, there are many on the Google store. From there you can connect to it with a simple address and port.

**Comment by phoenixg** [comment]
Hm.... I really don't understand what you mean.

**Comment by SkorrloreGaming** [comment]
Also I am recording this whole project in c# and doing a complete investigation on the coordinate system. It was hard asf to recode the initial setup code as I needed to code uint24 from scratch and understand how to send the client the packet without confliction. I also decided to a ssh tunnel package and key for the server frame as this one didn't come with one. Once it is operational and customizable I will release it as an organization and people can edit the code.

**Comment by phoenixg** [comment]
@SkorrloreGaming I hope you do the great job soon, I cannot wait to play.

**Comment by SkorrloreGaming** [comment]
I mean.. That you need a mod to connect to a private server, because unlike agario slither doesn't have a built in ip in address bar feature nor does it have a built in connect command. So you need to use a mod to connect to a server.

**Comment by qinxi** [comment]
same problem .
I changed the server  prot to 8000 .
run  dev/client  by nginx(8080) and change the ws port to 8000
but I  open the page .this image show 

![](https://dn-qinxim.qbox.me/test/339dfd30-1b96-445c-901c-079617f5bc0a.png)

**Comment by SkorrloreGaming** [comment]
You need to be on the slither.io *website* using a mod to connect to the server, the port needs to be forwarded for the server along with it being allowed through windows firewall in both private and public.

**Comment by RowanHarley** [comment]
@SkorrloreGaming you don't need a mod. You can simply open the console and type: sos = [{ ip: "localhost", po: 443, ac: 34, ptm: 121 }]
You can change the first 2 to suit your ip and port.

**Comment by SkorrloreGaming** [comment]
Thanks for the info, I will now make a server hosting service for slither.io that is based off of that console command.

**Comment by Logan7432** [comment]
:)

**Comment by iiegor** [comment]
Closing this since the issue was resolved.

**Comment by phoenixg** [comment]
I don't know what you are talking about the `mod` thing, I just want to play (cry), please make it as simple as possible. :)
