### ISSUE TITLE
I get 'Upgrade required' on the webpage

### ISSUE THREAD

**Issue by bazizi** [iiegor/slither#5]
When I run the bash script it works just fine:
behnam@LinuxNet> bash script/run                                                                                          /tmp/slither
[Application][DEBUG] You are running slither-server 0.0.3
[Application][INFO] Starting the server in dev at port 8080...
[Server][INFO] Listening on port 8080

But when I open up http://localhost:8080 all I get is:
Upgrade Required

Here is how the screenshot looks like:
![screenshot from 2016-04-17 10-54-45](https://cloud.githubusercontent.com/assets/7786414/14588936/d7f43136-048a-11e6-8035-e4b00be6e238.png)

Also:
behnam@LinuxNet> node --version                                                                                     /tmp/slither
v5.10.

behnam@LinuxNet> npm --version                                                                                            /tmp/slither
3.8.6

Any thoughts?

**Comment by iiegor** [comment]
@bazizi was resolved?

**Comment by bazizi** [comment]
Hi Iegor
Yes this particular issue was solved. Sorry I did not look at the previous issues before posting this. I was opening my browser to http://127.0.0.1:8080, which of course was not what I was supposed to do.

That being said, it looks like this project is not complete yet? I still could not connect to the slither.io server...
