### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by Mojotron3000** [iiegor/slither#50]
I am having no luck on installing this. I might just be really dumb. Maybe a little more detail would help? Thanks

**Comment by Qasimmodo** [comment]
Refer to #13

**Comment by Mojotron3000** [comment]
Worked!

**Comment by Babam456** [comment]
I realy need help installing this. I have little back ground in code but a huge passion for it. P.s I already checked number #13.

**Comment by RowanHarley** [comment]
@Babam456 create a new issue

**Comment by Babam456** [comment]
How do I do that?

**Comment by iiegor** [comment]
Please, don't create duplicated issues about the same thing, all the information about how to install and run the server can be found on the README and all the closed issues.

**Comment by Babam456** [comment]
Ok thankyou
