### ISSUE TITLE
[FIX] Glitchy Snake Bug [FIX]

### ISSUE THREAD

**Issue by InvincibleMiners** [iiegor/slither#56]
# **The issue**

The issue for most people is the snake is glitchy, instead of smooth

# **The Fix**
The fix for this is very simple:

Go you your Server folder:
![image](https://cloud.githubusercontent.com/assets/18273517/14972161/6ceb5e40-108e-11e6-887b-3930e5704671.png)

Then go to the folder "src"
![image](https://cloud.githubusercontent.com/assets/18273517/14972179/858ce572-108e-11e6-819e-15e4cdb64ac4.png)

Then go to "entities"
![image](https://cloud.githubusercontent.com/assets/18273517/14972197/92457e14-108e-11e6-85dc-d18e9fdf3714.png)

Select "snake.coffee" and open with [notepad++](https://notepad-plus-plus.org/download/v6.9.1.html)
![image](https://cloud.githubusercontent.com/assets/18273517/14972270/1e09baaa-108f-11e6-9631-244629f7d98c.png)

Now find where it says "@speed"
![image](https://cloud.githubusercontent.com/assets/18273517/14972273/24657be6-108f-11e6-96ff-bc9896c288b0.png)

Change "@speed = 5.79 * 1e3" to "@speed = .25 * 1e1"

Feel free to mess around, but this works good enough for me.

**Note that this **DOES** not work all the way, but it fixes the problem well!

**Comment by Crayder** [comment]
So why don't you make a pull request?

**Comment by InvincibleMiners** [comment]
@Crayder I am doing that atm. I just wanted to share this with everyone #skrublyfe2016

**Comment by vancourt** [comment]
im building an emulator from scratch, but is in c#, if anyone have interest to help here is the code to connect or add me on skype
adm_necros
sos = [{ ip: "151.80.111.227", po: 777, ac: 34, ptm: 121 }]

**Comment by Crayder** [comment]
@vancourt How is that at all related to this? You and your advertising... xD

**Comment by InvincibleMiners** [comment]
@Crayder lol

**Comment by RowanHarley** [comment]
Snake is still moving very fast when I change it.

**Comment by Ciao121** [comment]
It does not changes snake speed for me.

**Comment by rydens** [comment]
All the problem I see so far is that the snake is moving extremely fast.

**Comment by iiegor** [comment]
Changing the value of that variable won't fix the problem because it isn't used anywhere.

**Comment by InvincibleMiners** [comment]
@iiegor this fixed the problem for me...
