### ISSUE TITLE
Cloning original client?

### ISSUE THREAD

**Issue by HAlexTM** [iiegor/slither#58]
Hi, is this possible to clone (use original .js script) for an own client?
I don't think that is needed to have server original .js client's file, just what you see from your browser, isn't it XD?

**Comment by iiegor** [comment]
Please, read the closed issues before creating a new one. Yes, you can and a example is in the [``dev/client``](https://github.com/iiegor/slither/tree/dev/client) branch.

**Comment by HAlexTM** [comment]
Thank you a lot, and sorry
