### ISSUE TITLE
pither

### ISSUE THREAD

**Issue by Logan7432** [iiegor/slither#59]
Can we you this server with the client named pither?

**Comment by Crayder** [comment]
What the fuq is pither? I can't find anything about a slither client named pither.

Are you suggesting this project's client should be named pither? That would be dumb. This is purely just a server that you can connect to from slither.io.

**Comment by ItzLevvie** [comment]
He means this: https://github.com/PlitherProject/Plither

**Comment by Crayder** [comment]
Ah, p*l*ither... That makes more sense...

**Comment by Logan7432** [comment]
@ItzLevvie Yes thats what im talking about.

**Comment by Logan7432** [comment]
Pither client is just for pither servers because hey dont have a server that works for it ands its pretty much an exact clone of slither it should connect.

**Comment by iiegor** [comment]
At the moment this server is only focused on supporting the original slither client, sorry.
