### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by random321** [iiegor/slither#6]
"You can use the original one from slither.io, just go there, open the console, paste: `sos = [{ ip: "localhost", po: 8080, ac: 34, ptm: 121 }]` and press the play button."

Could you enlighten me some more? I can't figure this out.

**Comment by iiegor** [comment]
With your server open and listening at ``:8080``, just follow these steps:

1. Go to [slither.io](http://slither.io)
2. Open the devtools (you can do this pressing ctrl+shift+j)
3. Switch to the ``console`` tab.
4. Paste ``sos = [{ ip: "localhost", po: 8080, ac: 34, ptm: 121 }]`` and press ``play``

If you followed correctly this steps, should appear some logs in your sever window.

**Comment by random321** [comment]
Thank you very much :) 
I was now able to connect but am still waiting for the ability to move :P
