### ISSUE TITLE
[Bug] cannot move snake + weird movements

### ISSUE THREAD

**Issue by HAlexTM** [iiegor/slither#62]
So, I've built the server and when I connect to it with slither.io this is what I get :)
[Image (Gif)](http://i.imgur.com/YWAW20k.gif) (Wait the image for full load)

**Comment by ItzLevvie** [comment]
This is currently under extremely active development, and you probably shouldn't use it unless you like broken software..

**Comment by HAlexTM** [comment]
I know, I just reported a bug..

**Comment by iiegor** [comment]
Duplicated of https://github.com/iiegor/slither/issues/53
