### ISSUE TITLE
Do we have client app where to use this server?

### ISSUE THREAD

**Issue by mrmarktyy** [iiegor/slither#64]
Or does it support something like slither.io?ip=xxxx ? thanks !

**Comment by Crayder** [comment]
Use a slither.io extension or a user script.

There are many that let you connect by IP.

This server is intended to work for the original client.

**Comment by HAlexTM** [comment]
You can use the dev client branch for a client

**Comment by iiegor** [comment]
As @HAlexTM said, you can use the [dev/client](https://github.com/iiegor/slither/tree/dev/client) branch.  Another way is following [this instructions](https://github.com/iiegor/slither/issues/2#issuecomment-210875194) or using an extension as @Crayder said.
