### ISSUE TITLE
When I run the script in te localhost:8080 only show "Upgrade Required"

### ISSUE THREAD

**Issue by mermelado** [iiegor/slither#67]
This issue is experimented in local (windows) and remote server (centos) in two nodejs versions and slither-0.0.11.
Thanks.

**Comment by twosevenzero** [comment]
Read the old closed issues. https://github.com/iiegor/slither/issues/2 
You have to use the slither.io client.

**Comment by twosevenzero** [comment]
This should really be added to the README

**Comment by mermelado** [comment]
Thank you very much for the quick response and interesting project. But unfortunately still does not work for me. I do not quite understand how. I tried to put the ip and port of my web server in slither.io page (I have the mod to put ips) and it works, but does not leave any worms, only the stage.

**Comment by RowanHarley** [comment]
Just use localhost:8080

**Comment by mermelado** [comment]
If I use localhost:8080 obviusly get again Upgrade Required. And I whant use in remote server if is posibble..
Note: In the readme I don't read nothing about this.

**Comment by RowanHarley** [comment]
I meant stick localhost:8080 into the ip mod on slither.io

**Comment by mermelado** [comment]
In remote server don't can?

**Comment by thereis** [comment]
Close the thread.

**Comment by mermelado** [comment]
Close the thread.???
very enlightening answer.

**Comment by thereis** [comment]
Dude, you're question was solved. You don't know how to configure the server and you must know. "THIS IS NOT WORKING CORRECTLY".

If you want to improve the game, just catch the packets and try to fix yourself. For me, this work as well but if you don't know how to setup, its a problem for you, okay?

**Comment by RowanHarley** [comment]
@thereis how do you catch packets, just out of interest?

**Comment by mermelado** [comment]
RowanHarley:
I do not understand the comment, sorry.
you ask for I want I use your code?
  In any case thank you very much for all your help.
thereis, as for you, is not worth not answer, why ?. I do not write in forums to argue with anyone.

**Comment by iiegor** [comment]
Sorry, I don't understand, did you read the closed issues about the "Upgrade Required" message? What is your actual issue? Have in mind that the game is unplayable because the server is on development so if you are not a developer, installing this server doesn't makes any sense (unless you want to try things).

**Comment by mermelado** [comment]
That's just what happens to me, the client connects correctly but only get the background, there is no snake.
I'm not a developer, hopefully. I will wait for a stable version. Thank you so much for everything.

**Comment by iiegor** [comment]
That's strange, a snake should appear moving fastly :confused:

**Comment by mermelado** [comment]
If you want try it yourself in 149.202.60.130:8080
I have it on my OVH server and other local copy on my PC under Windows, both do the same, no snake.
Thanks.

**Comment by ModernMelon** [comment]
lol

**Comment by ferrnnaando** [comment]
wake ap bro is taim to go to the eskul
