### ISSUE TITLE
Newbie here

### ISSUE THREAD

**Issue by Jacobisahugecock** [iiegor/slither#69]
Can anyone tell me how to transfer this repo into a herokuapp?

If that isn't possible please do tell, but I've usually relied on easy setups.

**Comment by iiegor** [comment]
What is the problem? Just push the server files to heroku and it will do all for you.

**Comment by kleinarcade** [comment]
The thing is. I have no idea how to do it. Anytime that I see instructions in like these weird code looking text boxes, it's just text. I have no idea how to perform that.
