### ISSUE TITLE
Server start but can't connect and no logs

### ISSUE THREAD

**Issue by iioel** [iiegor/slither#7]
Hey, I've try to run the server but I can't connect to him ( "sos = [{ip: "127.0.0.1", po: 8080, ac: 132, ptm: 12}];" ) and no more logs appear on the console.

`me@me-My-Desktop:~/slither-0.0.3$ bin/slither`
`[Application][DEBUG] You are running slither-server 0.0.3`
`[Application][INFO] Starting the server in dev at port 8080...`
`[Server][INFO] Listening on port 8080`

I've also try to start `server.js` : 

`me@me-PC-Desktop:~/slither-0.0.3$ node server.js `
`module.js:341`
`    throw err;`
`    ^`

`Error: Cannot find module './bin/kekocity'`
`    at Function.Module._resolveFilename (module.js:339:15)`
`    at Function.Module._load (module.js:290:25)`
`    at Module.require (module.js:367:17)`
`    at require (internal/module.js:16:19)`
`    at Object.<anonymous> (/home/yoel/slither-0.0.3/server.js:1:63)`
`    at Module._compile (module.js:413:34)`
`    at Object.Module._extensions..js (module.js:422:10)`
`    at Module.load (module.js:357:32)`
`    at Function.Module._load (module.js:314:12)`
`    at Function.Module.runMain (module.js:447:10)`
`me@me-PC-Desktop:~/slither-0.0.3$ `

**Comment by iiegor** [comment]
Hey @iioel, when the server outputs ``Listening on port 8080`` all should be ready so maybe you did something wrong when setting the ``sos`` variable value. Did you tried following the instructions given here: https://github.com/iiegor/slither/issues/6#issuecomment-211077549?

**Comment by iioel** [comment]
@iiegor I've followed the instructions but same, I can't connect to the server. Perhaps an node version problem ?

**Comment by iiegor** [comment]
@iioel I updated my comment, check again ;)

**Comment by iioel** [comment]
@iiegor Yeah, thanks it work !
