### ISSUE TITLE
When is next update planned?

### ISSUE THREAD

**Issue by RowanHarley** [iiegor/slither#70]
Just out of ineterest, when will the next update be coming out. The last update was about a week ago (don't say it!). Is it just because you are having trouble finding time or are you waiting to release one big update?

**Comment by iiegor** [comment]
@RowanHarley Sorry, I've been busy this week, I will try to find some time for the project :+1:

**Comment by RowanHarley** [comment]
Thats fine @iiegor just wanted to know whats happening atm
