### ISSUE TITLE
Upgrade Required

### ISSUE THREAD

**Issue by quoc1506** [iiegor/slither#71]
I try to access like client but I catch this issue: Upgrade Required

**Comment by ItzLevvie** [comment]
Read https://github.com/iiegor/slither/issues/6#issue-148977725

**Comment by quoc1506** [comment]
![screen shot 2016-05-13 at 1 54 01 pm](https://cloud.githubusercontent.com/assets/13410920/15240177/f7e19844-1911-11e6-8db5-b839ff51308c.png)
I cannot connect to localhost?

**Comment by RowanHarley** [comment]
I've noticed this problem as well. I think the only way to connect now is through mods

**Comment by ItzLevvie** [comment]
I can connect to my server, without using mods.

**Comment by iiegor** [comment]
Slither has updated their client, setting the value of the `sos = [..]` variable is no longer a valid method.

**Comment by thapakazi** [comment]
I still have the same issue... 
Any workarounds ?
