### ISSUE TITLE
When connecting to slither server I get "upgrade required" in the top left corner and the rest is blank

### ISSUE THREAD

**Issue by 1823alex** [iiegor/slither#73]
Seems like a bug or something any ideas why this is? I'm running RHEL7 and followed install instructions server says it is listening for connection, so I have no idea what is going on here. I am running Slither 0.0.12-dev. It says starting the server in dev is there an option or command I need to run to fix this or what?

**Comment by RowanHarley** [comment]
This is not a bug. You need to use slither.io to connect, not localhost:8080. You will also need to have installed mods so that you can connect to the server
