### ISSUE TITLE
no food in my map

### ISSUE THREAD

**Issue by ZzerLo** [iiegor/slither#75]
there is no food and no one else on my network can see each other

**Comment by RowanHarley** [comment]
Are you using a port forwarder like hamachi?

**Comment by ZzerLo** [comment]
No I am just playing on my local home network ( using my ipV6 address)so
that is not needed

**Comment by RowanHarley** [comment]
I'm talking about when you play with friends. You need a port-forwarder like Hamachi to connect friends together.

**Comment by RowanHarley** [comment]
And you should be seeing food. I've seen it when I play although this project is in alpha stage and there  are many bugs

**Comment by ZzerLo** [comment]
You should be able to just play by connecting to my ip address on my local
network... The friends are also on my network. I know how networking works
very well.

**Comment by RowanHarley** [comment]
This mightn't be fully implemented into the server-side yet. Not sure though, never really tryed it.

**Comment by thorvn** [comment]
I don't see food in my map. Have anyone help me?
