### ISSUE TITLE
When is next update planned?

### ISSUE THREAD

**Issue by RowanHarley** [iiegor/slither#77]
13 days since last update! 😢 can u please update this soon

**Comment by Crayder** [comment]
This is not what GitHub is for. You don't make issues because you feel like developers should be updating things every damn hour. He has his own life too ya know.

**Comment by AlexDicy** [comment]
He has already done a lot of work, there are bug yeah, as this is a free project someone could help instead of asking for updates

**Comment by RowanHarley** [comment]
That would be good. I'd love to keep this project going but I don't have a clue about coffeescript. If this was js I would be able to help

**Comment by iiegor** [comment]
@RowanHarley CoffeeScript compiles to JavaScript so it's almost the same thing, just a shorter way to write code. If you know JavaScript you will know also coffee, see http://coffeescript.org/.
