### ISSUE TITLE
Working out code

### ISSUE THREAD

**Issue by RowanHarley** [iiegor/slither#79]
I'm having a look at some of the code but there seem to be some bits of algorithm I don't understand. Here's the code I'm struggling with:

`arr = new Uint8Array((8 + length) + (top.length * 7))`

I'm still looking through the code so I might have to add more.

**Comment by rockthrower69** [comment]
Can u give some context? I dont know what `length` and `top` are so I can't explain it

**Comment by RowanHarley** [comment]
this comes from https://github.com/iiegor/slither/blob/master/src/messages/leaderboard.coffee#L11

**Comment by ItzLevvie** [comment]
JavaScript version of leaderboard.coffee
```
var math, message, type;

message = require('../utils/message');

math = require('../utils/math');

type = 'l'.charCodeAt(0);

exports.build = function(rank, players, top) {
    var arr, b, i, j, len, length, player;
    length = 0;
    for (j = 0, len = top.length; j < len; j++) {
        player = top[j];
        length += player.snake.name.length;
    }
    arr = new Uint8Array((8 + length) + (top.length * 7));
    b = 0;
    b += message.writeInt8(b, arr, 0);
    b += message.writeInt8(b, arr, 0);
    b += message.writeInt8(b, arr, type);
    b += message.writeInt8(b, arr, 0);
    b += message.writeInt16(b, arr, rank);
    b += message.writeInt16(b, arr, players);
    i = 0;
    while (i < top.length) {
        b += message.writeInt16(b, arr, top[i].snake.J);
        b += message.writeInt24(b, arr, top[i].snake.I);
        b += message.writeInt8(b, arr, math.randomInt(0, 8));
        b += message.writeInt8(b, arr, top[i].snake.name.length);
        b += message.writeString(b, arr, top[i].snake.name);
        i++;
    }
    return arr;
};
```

**Comment by vancourt** [comment]
this code will create a array of byte based on length
arr = new Uint8Array([size of array])

so you need get all the packet size before create the array of 8 byte

**Comment by rockthrower69** [comment]
When you create a packet, you have to send a Uint8Array. To make this you have to set the length before adding stuff. In this case you want to send `player.snake.name` and `players`.
The packet is 8 bytes long (line 14 - 22) + the length of the name + all the players with each 7 bytes (line 26 - 32).
