### ISSUE TITLE
Server Not Starting/Working

### ISSUE THREAD

**Issue by guccibum1** [iiegor/slither#81]
[Server][DEBUG] Connection closed.
[Server][ERROR] Unhandled message s -  null"

What does this mean??﻿

Thank You

**Comment by AlexDicy** [comment]
What version are you using?

**Comment by iiegor** [comment]
@guccibum1 take a look at the closed issues.

**Comment by guccibum1** [comment]
How do i check

**Comment by AlexDicy** [comment]
https://github.com/iiegor/slither/issues?q=is%3Aissue+is%3Aclosed
