### ISSUE TITLE
Error in snake code?

### ISSUE THREAD

**Issue by RowanHarley** [iiegor/slither#85]
While looking through your code, I was comparing it to Slither.io Protocol and I noticed that [this line](https://github.com/iiegor/slither/src/messages/snake.coffee#L21) seemed to be wrong. What I seen on  the [Slither.io Protocol](https://github.com/ClitherProject/Slither.io-Protocol/blob/master/Protocol.md#type_s_detail) was 

> Snake angle eang / wang (value \* 2 \* Math.PI / 16777215)

but you had `snake.D`. Is this an mistake in code or is this equation carried out somewhere else?

**Comment by ItzLevvie** [comment]
https://github.com/iiegor/slither/blob/master/src/entities/snake.coffee#L13

**Comment by RowanHarley** [comment]
oh, didn't even see that! Thanks anyways!
