### ISSUE TITLE
How to join from the client?

### ISSUE THREAD

**Issue by markasoftware** [iiegor/slither#89]
How can I join the game from the browser? I've successfully started up the server and all. It says in the readme that I can use the default client; how would I do that?

**Comment by Crayder** [comment]
Get a chrome extension that allows you to connect to servers by IP:PORT

You should know what your IP and port number are, so all you do is put it in and connect

**Comment by RowanHarley** [comment]
If you don't want to download extensions,you can use Ctrl + Shift + J to open console then type `forceServer ("127.0.0.1",8080);`

**Comment by markasoftware** [comment]
Ok, thanks that works.
