### ISSUE TITLE
Error Installing

### ISSUE THREAD

**Issue by slipzdev** [iiegor/slither#90]
Trying to install, everything I need is there, but whenever I run "npm install" OR "npm start", command prompt just spams "F:\Slither\npm install/start". Any help?

**Comment by RowanHarley** [comment]
Are you sure you're using Node's dedicated console and are on the right directory?

**Comment by slipzdev** [comment]
Yes I'm in the directory, and node has a dedicated console? I'm just using regular command prompt.

**Comment by slipzdev** [comment]
@RowanHarley Oh, thanks! I fixed it. I didnt run in Node's console (which I didnt even know existed xD). But that worked! Thank you!
