### ISSUE TITLE
I Need some Help

### ISSUE THREAD

**Issue by GodzGamer** [iiegor/slither#92]
Ok so I Install The npm And Tried to start the server but need some help cus it wont launch can anyone help me with step by step process ( i am a youtuber and need a slither server for gameplay and livestreams)

**Comment by dmbekker** [comment]
> This is currently under extremely active development, and you probably shouldn't use it unless you like broken software.

— As clearly stated in the readme.

I cannot recommend using this for your Youtube video's..

**Comment by GodzGamer** [comment]
Ok thats Totally Fine Thx for Your Response

**Comment by RowanHarley** [comment]
@dmbekker The problem he's having is with the installation, not the software itself which means that the quote given is wrong. @GodzGamer did you use the node.js command prompt?

**Comment by GodzGamer** [comment]
Yes I Did
And I Kinda Managed to run the server but i cant connect to it

**Comment by RowanHarley** [comment]
So when you ran the server you got some messages like:

> [DEBUG] Server started! Waiting for connections...

If you got messages like that, then you're probably trying to connect in the wrong way. When you try to connect, what do you do?

**Comment by GodzGamer** [comment]
i use the extension and add my ip in it with port 8080

**Comment by RowanHarley** [comment]
Hmmm... Maybe the extension is the problem? Try opening the js console (Ctrl + Shift + J) and typing in `forceServer("localhost", 8080);`
