### ISSUE TITLE
Please help me if anyone can!

### ISSUE THREAD

**Issue by archangel72** [iiegor/slither#94]
I'm new and i don't know that how to execute these files. please help me step by step. I already install node.js  and i tried to execute that snake.js but nothings happen!!. help me please if u can.

**Comment by RowanHarley** [comment]
Use npm start inside node.js's dedicated command prompt

**Comment by archangel72** [comment]
i use command "npm start snake.js" but it throw multiple errors. please help me step-by-step that how to exactly start it.

**Comment by Crayder** [comment]
Off topic, told you guys he'd be back. He closed this issue, there's your proof.

**Comment by archangel72** [comment]
but my problem isnt solved yet

**Comment by RowanHarley** [comment]
Use just `npm start`, not `npm start snake.js`
